site_name: My First MkDocs
site_dir: public

nav:
  - Home: index.md
  - Angular筆記:
      - "第一章 前端網頁應用的利器Angular": angularPage/part1/mod01.md
      - "第二章 Module 與 MVC 設計模型": angularPage/part1/mod02.md
      - "第三章 初探 Angular Route & Navigation": angularPage/part1/mod03.md
      - "第四章 HTML Binding 與 Event 的處理r": angularPage/part1/mod04.md
      - "第五章 關於 UI 的那些是 —元件、指令、Pipe": angularPage/part1/mod05.md
      - "第六章 表單 (Form)": angularPage/part1/mod06.md
      - "第七章 表單驗證": angularPage/part1/mod07.md
      - "第八章 Service (DI: 依存注入) 與 HttpClient": angularPage/part1/mod08.md
      - "第九章 ASP.NET Core Web API 與 Entity Framework Core": angularPage/part1/mod09.md
      - "第十章": angularPage/part1/mod10.md
      - "第十一章": angularPage/part1/mod11.md
  - CSS框架: 
      - "CSS框架": cssFrameworks/index.md
      - "Bootstrap": cssFrameworks/bootstrap.md
      - "Material UI": cssFrameworks/materialUI.md
      - "Tailwind CSS": cssFrameworks/tailwindCss.md
  - TypeScript: typeScriptPage/index.md
  - markdown語法: markdownPage/index.md

theme:
  name: material
  logo: assets/Angular.png
  features:
    # 即時載入
    - navigation.instant
    # 進度指示器
    - navigation.instant.progress
    # 導航選項卡
    - navigation.tabs
    # 側邊欄群組
    - navigation.sections
    - navigation.indexes
    # 上方呈現麵包屑導航
    - navigation.path
    # 返回頂部按鈕
    - navigation.top

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
extra:
  # 設定頁腳連結
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/uliang1024
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/uliang0230/

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      annotation: material/arrow-right-circle

plugins:
  - search:
      lang: ja

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # 內容選項卡
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  # Data tables
  - tables
  #Plugins for MkDocs
  - neoteroi.timeline

extra_css:
    - assets/css/extra.css
    - assets/css/neoteroi-timeline.css

extra_javascript:
  - assets/js/script.js